config/routes.rb
# == Route Map
#
# You don't have any routes defined!
# 
# Please add some routes in config/routes.rb.
# 
# For more information about routes, see the Rails guide: http://guides.rubyonrails.org/routing.html.
# 

Rails.application.routes.draw do
  scope constraints: lambda { |r| r.env['warden'].user.nil?} do
    get "signup", to: "users#new", as: "signup"
    get "login", to: "sessions#create", as: "login"
  end

  get "logout", to: "sessions#destroy", as: "logout"
  
  root to: "catalog#index"

  resources :users

  resources :sessions

  resources :orders do 
    get 'meus_pedidos', on: :collection
    get 'meus_pedidos/detalhes_pedido/:sales_order_id', to: 'orders#detalhes_pedido', as: 'detalhes_pedido'
  end


  resources :catalog, only: [:index, :show] do 
    get :index2, on: :collection
  end

  get 'meu_carrinho', to: 'cart#meu_carrinho', as: 'meu_carrinho'
  get 'add_quantidade_item', to: 'cart#add_quantidade_item', as: 'add_quantidade_item'
  get 'remove_quantidade_item', to: 'cart#remove_quantidade_item', as: 'remove_quantidade_item'
  get 'altera_quantidade_item', to: 'cart#altera_quantidade_item', as: 'altera_quantidade_item'
  get 'abre_modal', to: 'cart#abre_modal', as: 'abre_modal'

  post 'add_item/:product_id', to: 'cart#add_item', as: 'add_item'
  post 'fecha_pedido', to: 'cart#fecha_pedido', as: 'fecha_pedido'

  delete 'remove_item', to: 'cart#remove_item', as: 'remove_item'
  delete 'limpa_carrinho', to: 'cart#limpa_carrinho', as: 'limpa_carrinho'

  namespace :admin do
    resources :administrators
    resources :products
    resources :sessions
    resources :price_tables do
      resources :product_price_tables  
    end

    get 'login', to: 'sessions#new', as: 'login'
    post 'login', to: 'sessions#create', as: 'authenticate'
    get 'logout', to: 'sessions#destroy', as: 'logout'

    get 'pedidos', to: 'dashboard#pedidos', as: 'pedidos'
    get 'pedidos/detalhes_pedido/:pedido_id', to: 'dashboard#detalhes_pedido', as: 'detalhes_pedido'
    get 'exportar_lista_produtos', to: 'dashboard#exportar_lista_produtos', as: 'exportar_lista_produtos'
    post 'importar_produtos', to: 'dashboard#importar_produtos', as: 'importar_produtos'
  end

end

app/models/administrator.rb
# == Schema Information
#
# Table name: administrators
#
#  id              :integer          not null, primary key
#  name            :string           not null
#  email           :string           not null
#  password_digest :string           not null
#  active          :boolean          not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class Administrator < ApplicationRecord
  has_secure_password
end

app/controllers/admin/administrators_controller.rb
class Admin::AdministratorsController < Admin::BaseController
  before_action :set_administrator, only: [:show, :edit, :update, :destroy]

  def index
    @administrators = Administrator.all
    @products = Product.group(:status).count
    @disponiveis = @products['disponivel'].to_i
    @indisponiveis = @products['indisponivel'].to_i
    @pronta_entregas = @products['pronta_entrega'].to_i
    @esgotados = @products['esgotado'].to_i
  end

  def show
  end

  def new
    @administrator = Administrator.new
  end

  def edit
  end

  def create
    @administrator = Administrator.new(administrator_params)

    respond_to do |format|
      if @administrator.save
        format.html { redirect_to @administrator, notice: 'Administrator was successfully created.' }
        format.json { render :show, status: :created, location: @administrator }
      else
        format.html { render :new }
        format.json { render json: @administrator.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @administrator.update(administrator_params)
        format.html { redirect_to @administrator, notice: 'Administrator was successfully updated.' }
        format.json { render :show, status: :ok, location: @administrator }
      else
        format.html { render :edit }
        format.json { render json: @administrator.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @administrator.destroy
    respond_to do |format|
      format.html { redirect_to administrators_url, notice: 'Administrator was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_administrator
      @administrator = Administrator.find(params[:id])
    end

    def administrator_params
      params.fetch(:administrator, {})
    end
end

app/helpers/administrators_helper.rb
module AdministratorsHelper
  def total_produtos
    total = Product.all.size
    return total
  end
end

app/views/admin/administrators/_form.html.erb
<%= form_for [:admin, @administrator] do |f| %>

<ul>
  <% @administrator.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
  <% end %>
</ul>

<div class="field">
  <p>
    Name: <%= f.text_field :name, class:"form-control form-control-sm"%>
  </p>

  <p>
    E-mail: <%= f.text_field :email, class:"form-control form-control-sm"%>
  </p>

  <p>
    Password: <%= f.password_field :password, class:"form-control form-control-sm"%> 
  </p>
</div>

<br/> <br/>
<p>
  <%= f.submit 'Salvar', class:"btn btn-primary" %>
</p>

<% end %>

app/views/admin/administrators/_lista_produtos.html.erb
<div class="col-md-5 order-md-2 mb-10 card card-body bg">
  <h4 class="d-flex justify-content-between align-items-center mb-3">
    <span class="text-muted">Produtos Cadastrados</span>
    <span class="badge badge-secondary badge-pill"><%= total_produtos %></span>
  </h4>
  <ul class="list-group mb-3">
    <li class="list-group-item d-flex justify-content-between lh-condensed">
      <div>
        <h6 class="my-0">Disponiveis</h6>
      </div>
      <span class="badge badge-success"><%= @disponiveis %></span> 
    </li>
    <li class="list-group-item d-flex justify-content-between lh-condensed">
      <div>
        <h6 class="my-0">Indisponiveis</h6>
      </div>
      <span class="badge badge-danger"><%= @indisponiveis %></span>
    </li>
    <li class="list-group-item d-flex justify-content-between lh-condensed">
      <div>
        <h6 class="my-0">Pronta Entrega</h6>
      </div>
      <span class="badge badge-primary"><%= @pronta_entregas %></span>
    </li>
    <li class="list-group-item d-flex justify-content-between lh-condensed">
      <div>
        <h6 class="my-0">Esgotados</h6>
      </div>
      <span class="badge badge-warning"><%= @esgotados %></span>
    </li>
    <li class="list-group-item d-flex justify-content-between lh-condensed">
      <div class="btn-group">
        <%= link_to 'Lista de Todos Produtos', admin_exportar_lista_produtos_path(format: :csv), class:"btn btn-info" %>
        <button type="button" class="btn btn-info dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <span class="sr-only">Toggle Dropdown</span>
        </button>
        <div class="dropdown-menu">
          <%= link_to 'Produtos Dispniveis', admin_exportar_lista_produtos_path(format: :csv, 
          status: tipo_exportacao_produtos("disponivel")) , class:"dropdown-item" if @disponiveis != 0 %>
          <%= link_to 'Produtos Indisponiveis', admin_exportar_lista_produtos_path(format: :csv, 
          status: tipo_exportacao_produtos("indisponivel")), class:"dropdown-item" if @indisponiveis != 0 %>
          <%= link_to 'Produtos Pronta Entrega', admin_exportar_lista_produtos_path(format: :csv, 
          status: tipo_exportacao_produtos("pronta_entrega")), class:"dropdown-item" if @pronta_entregas != 0 %>
          <%= link_to 'Produtos Esgotados', admin_exportar_lista_produtos_path(format: :csv, 
          status: tipo_exportacao_produtos("esgotado")), class:"dropdown-item" if @esgotados!= 0 %>
        </div>
      </div>
    </li>
    <li class="list-group-item d-flex justify-content-between lh-condensed"> 
      <%= form_tag admin_importar_produtos_path, multipart: :true, remote: :true do %>
      <%= file_field_tag :csv %>
      <br/> <br/>
      <%= submit_tag 'Importar Produtos' %>
      <% end %>
    </li>
  </div>

app/views/admin/administrators/_navbar.html.erb
<% if current_administrator.present? %>
<nav class="navbar navbar-expand-lg navbar navbar-dark bg-dark">
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <a class="btn btn-dark dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Menu
    </a>
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
          <%= link_to 'Produtos', admin_products_path, class:"dropdown-item" %>
          <%= link_to 'Tabela de Preço', admin_price_tables_path, class:"dropdown-item" %>
        </div>
      </li>
      <li class="nav-item">
        <%= link_to 'Pedidos', admin_pedidos_path, class:"btn btn-dark" %>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <div class="dropdown">
        <a class="btn btn-dark dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <span> <%= current_administrator.name %> </span>
        </a>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
          <%= link_to 'Logout', admin_logout_path, class:"dropdown-item" %>
        </div>
      </div>
    </form>
  </div>
</nav>
<% end %>

app/views/admin/administrators/edit.html.erb
<h1>Editing Administrator</h1>

<%= render 'form', administrator: @administrator %>

app/views/admin/administrators/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Painel de Controle</h1>

<br/>

<div class="row" id="lista_produtos">
  <%= render 'lista_produtos' %>
</div>

<br/>

app/views/admin/administrators/new.html.erb
<h1>New Administrator</h1>

<%= render 'form', administrator: @administrator %>

app/views/admin/administrators/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_administrator_path(@administrator) %> |
<%= link_to 'Back', administrators_path %>