config/routes.rb
# == Route Map
#
# You don't have any routes defined!
# 
# Please add some routes in config/routes.rb.
# 
# For more information about routes, see the Rails guide: http://guides.rubyonrails.org/routing.html.
# 

Rails.application.routes.draw do
  scope constraints: lambda { |r| r.env['warden'].user.nil?} do
    get "signup", to: "users#new", as: "signup"
    get "login", to: "sessions#create", as: "login"
  end

  get "logout", to: "sessions#destroy", as: "logout"
  
  root to: "catalog#index"

  resources :users

  resources :sessions

  resources :orders do 
    get 'meus_pedidos', on: :collection
    get 'meus_pedidos/detalhes_pedido/:sales_order_id', to: 'orders#detalhes_pedido', as: 'detalhes_pedido'
  end


  resources :catalog, only: [:index, :show] do 
    get :index2, on: :collection
  end

  get 'meu_carrinho', to: 'cart#meu_carrinho', as: 'meu_carrinho'
  get 'add_quantidade_item', to: 'cart#add_quantidade_item', as: 'add_quantidade_item'
  get 'remove_quantidade_item', to: 'cart#remove_quantidade_item', as: 'remove_quantidade_item'
  get 'altera_quantidade_item', to: 'cart#altera_quantidade_item', as: 'altera_quantidade_item'
  get 'abre_modal', to: 'cart#abre_modal', as: 'abre_modal'

  post 'add_item/:product_id', to: 'cart#add_item', as: 'add_item'
  post 'fecha_pedido', to: 'cart#fecha_pedido', as: 'fecha_pedido'

  delete 'remove_item', to: 'cart#remove_item', as: 'remove_item'
  delete 'limpa_carrinho', to: 'cart#limpa_carrinho', as: 'limpa_carrinho'

  namespace :admin do
    resources :administrators
    resources :products
    resources :sessions
    resources :price_tables do
      resources :product_price_tables  
    end

    get 'login', to: 'sessions#new', as: 'login'
    post 'login', to: 'sessions#create', as: 'authenticate'
    get 'logout', to: 'sessions#destroy', as: 'logout'

    get 'pedidos', to: 'dashboard#pedidos', as: 'pedidos'
    get 'pedidos/detalhes_pedido/:pedido_id', to: 'dashboard#detalhes_pedido', as: 'detalhes_pedido'
    get 'exportar_lista_produtos', to: 'dashboard#exportar_lista_produtos', as: 'exportar_lista_produtos'
    post 'importar_produtos', to: 'dashboard#importar_produtos', as: 'importar_produtos'
  end

end

app/controllers/admin/dashboard_controller.rb
require 'csv'
class Admin::DashboardController < Admin::BaseController

  def pedidos
    @user = User.all
    @pedidos = SalesOrder.where(status: 'finalizado')
    @pedidos = @pedidos.where("user_id = ?", params[:usuario_escolhido]) if params[:usuario_escolhido].present?

    respond_to do |format|
      format.html { @pedidos = @pedidos.page(params[:page]).per(5) }
      format.js { @pedidos = @pedidos.page(params[:page]).per(5) }
      format.csv do
        documento = SalesOrder.gera_pedidos_csv(@pedidos.includes(:user))
        send_data documento[:csv].encode(Encoding::ISO_8859_1), filename: "pedidos_#{documento[:date]}.csv"
      end
    end
  end

  def detalhes_pedido
    @detalhes_pedido = SalesOrder.includes(:items).where(user_id: params[:user_id], id: params[:pedido_id])
    @detalhes_pedido = @detalhes_pedido.first
  end

  def exportar_lista_produtos
    status = params[:status]

    #Caso nenhum parametro seja passado, busca por todos produtos
    if status.blank?
      @produtos = Product.includes(:product_images).all.order('code')
    else
      @produtos = Product.includes(:product_images).where(status: status).order('code')
    end

    respond_to do |format|
      format.csv do 
        documento = Product.exportar_lista_produtos(@produtos)
        send_data documento[:csv].encode(Encoding::ISO_8859_1), filename: "produtos_#{documento[:date]}.csv"
      end
    end
  end

  def importar_produtos
    if !params[:csv].present?
      render :arquivo_faltando
    else
      Product.importar_produtos(params[:csv])
      render :import_realizado
    end
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/admin/dashboard/_navbar.html.erb
<% if current_administrator.present? %>
<nav class="navbar navbar-expand-lg navbar navbar-dark bg-dark">
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <a class="btn btn-dark dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Menu
    </a>
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
          <%= link_to 'Home', admin_administrators_path, class:"dropdown-item" %>
          <%= link_to 'Produtos', admin_products_path, class:"dropdown-item" %>
          <%= link_to 'Tabela de Preço', admin_price_tables_path, class:"dropdown-item" %>
        </div>
      </li>
      <li class="nav-item">
        <%= link_to 'Pedidos', admin_pedidos_path, class:"btn btn-dark" %>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <div class="dropdown">
        <a class="btn btn-dark dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <span> <%= current_administrator.name %> </span>
        </a>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
          <%= link_to 'Logout', admin_logout_path, class:"dropdown-item" %>
        </div>
      </div>
    </form>
  </div>
</nav>
<% end %>

app/views/admin/dashboard/_tabela_pedidos_clientes.html.erb
<br/>
<table class="table table-striped">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Cliente</th>
      <th scope="col">Data do Pedido</th>
      <th scope="col">Valor Total</th>
      <th scope="col">Status</th>
      <th> </th> 
    </tr>
  </thead>
  <tbody>
    <% @pedidos.includes(:user).each do |pedido| %>
    <tr>
      <td> 
        <%= pedido.user.name %>
      </td>
      <td>
        <%= pedido.created_at.strftime("%d/%m/%Y") %>
      </td>
      <td>
        $ <span class="badge badge-success"> <%= pedido.amount %> </span>
      </td>
      <td>
        <%= pedido.status.humanize %> </span>
      </td>
      <td> 
        <%= link_to 'Detalhes', admin_detalhes_pedido_path(user_id: pedido.user.id, pedido_id: pedido.id), 
            class: "btn btn-primary" %>
      </td>
    </tr>
  <% end %>
 </tbody>
</table>

app/views/admin/dashboard/arquivo_faltando.js.erb
alert('Selecione algum arquivo para realizar a importação');

app/views/admin/dashboard/detalhes_pedido.html.erb
<br/>
<h1> Meu Pedido: <%= @detalhes_pedido.id %> </h1>
<br/>

<table class="table table-borderless">
  <thead>
    <tr>
      <th> Usuario: <%= @detalhes_pedido.user.name %> </th>
      <th> Valor do Pedido: $ <span class="badge badge-success"> <%= @detalhes_pedido.amount %> </span> </th>
      <th> Data do Pedido: <%= @detalhes_pedido.created_at.strftime("%d/%m/%Y") %> </th>
      <th> </th>
      <th> </th>
    </tr>
    <tr>
      <th> Observações do Pedido: <%= @detalhes_pedido.notes %> </th>
      <th> </th>
      <th> </th>
      <th> </th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th> <h1> Itens </h1> </th>
    </tr>
    <tr>
      <th> Imagem </th>
      <th> Nome </th>
      <th> Preço do Produto </th>
      <th> Quantidade </th>
    </tr>
    <% @detalhes_pedido.items.includes(:product).each do |item| %>
    <tr>
      <td> 
        <%= image_tag product_has_image(item.product), height:'100', width:'100',class:"img-thumbnail" %>
      </td>
      <td> <strong> <%= item.product.name %> </strong> </td>
      <td> <strong> <%= item.price %> </strong> </td>
      <td> <strong> <%= item.amount %> </strong> </td>
    </tr>
  <% end %>
 </tbody>
</table>

<br/>

<%= link_to 'Voltar', admin_pedidos_path , class:"btn btn-warning" %>

<br/>

app/views/admin/dashboard/import_realizado.js.erb
alert('Produtos Importados com Sucesso');
window.location.assign("/admin/administrators/");

app/views/admin/dashboard/pedidos.html.erb
<br/>
<h2> Pedidos </h2>
<hr/>

<%= form_tag("/admin/pedidos", method: "get", remote: :true, id: 'frm_pesquisar', class:"form-inline") do %>
  <%= select_tag "usuario_escolhido", options_from_collection_for_select(@user, "id", "name"), 
  prompt: "Usuarios", class:"form-control form-control-sm" %> 
  &nbsp; &nbsp;
  <div class="input-group-append">
    <%= submit_tag 'Filtrar', id: 'btnPesquisar', class:"btn btn-primary" %>
  </div>
  &nbsp; &nbsp;
  <div id='link_download'>
    <%= link_to 'Download', admin_pedidos_path(format: :csv, usuario_escolhido: params[:usuario_escolhido]) %> <br/>
  </div>
<% end %> 

<br/>

<div class="row" id="tabela">
  <%= render 'tabela_pedidos_clientes' %>
</div>

<div id="paginacao"> 
  <%= paginate @pedidos, remote: true ,class:"page-item" %>
</div>

app/views/admin/dashboard/pedidos.js.erb
$('#tabela').html('<%= escape_javascript(render 'tabela_pedidos_clientes') %>');
$('#paginacao').html('<%= escape_javascript(paginate(@pedidos, :remote => true).to_s) %>');
$('#link_download').html('<%= escape_javascript(link_to "Download", admin_pedidos_path(format: :csv, usuario_escolhido: params[:usuario_escolhido]))%> ');