config/routes.rb
# == Route Map
#
# You don't have any routes defined!
# 
# Please add some routes in config/routes.rb.
# 
# For more information about routes, see the Rails guide: http://guides.rubyonrails.org/routing.html.
# 

Rails.application.routes.draw do
  scope constraints: lambda { |r| r.env['warden'].user.nil?} do
    get "signup", to: "users#new", as: "signup"
    get "login", to: "sessions#create", as: "login"
  end

  get "logout", to: "sessions#destroy", as: "logout"
  
  root to: "catalog#index"

  resources :users

  resources :sessions

  resources :orders do 
    get 'meus_pedidos', on: :collection
    get 'meus_pedidos/detalhes_pedido/:sales_order_id', to: 'orders#detalhes_pedido', as: 'detalhes_pedido'
  end


  resources :catalog, only: [:index, :show] do 
    get :index2, on: :collection
  end

  get 'meu_carrinho', to: 'cart#meu_carrinho', as: 'meu_carrinho'
  get 'add_quantidade_item', to: 'cart#add_quantidade_item', as: 'add_quantidade_item'
  get 'remove_quantidade_item', to: 'cart#remove_quantidade_item', as: 'remove_quantidade_item'
  get 'altera_quantidade_item', to: 'cart#altera_quantidade_item', as: 'altera_quantidade_item'
  get 'abre_modal', to: 'cart#abre_modal', as: 'abre_modal'

  post 'add_item/:product_id', to: 'cart#add_item', as: 'add_item'
  post 'fecha_pedido', to: 'cart#fecha_pedido', as: 'fecha_pedido'

  delete 'remove_item', to: 'cart#remove_item', as: 'remove_item'
  delete 'limpa_carrinho', to: 'cart#limpa_carrinho', as: 'limpa_carrinho'

  namespace :admin do
    resources :administrators
    resources :products
    resources :sessions
    resources :price_tables do
      resources :product_price_tables  
    end

    get 'login', to: 'sessions#new', as: 'login'
    post 'login', to: 'sessions#create', as: 'authenticate'
    get 'logout', to: 'sessions#destroy', as: 'logout'

    get 'pedidos', to: 'dashboard#pedidos', as: 'pedidos'
    get 'pedidos/detalhes_pedido/:pedido_id', to: 'dashboard#detalhes_pedido', as: 'detalhes_pedido'
    get 'exportar_lista_produtos', to: 'dashboard#exportar_lista_produtos', as: 'exportar_lista_produtos'
    post 'importar_produtos', to: 'dashboard#importar_produtos', as: 'importar_produtos'
  end

end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id         :integer          not null, primary key
#  code       :string           not null
#  name       :string           not null
#  deleted    :boolean
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  status     :integer          not null
#

class Product < ApplicationRecord
  after_update_commit :verifica_imagem_padrao
  validates :code, presence: true, uniqueness: true
  validates :name, presence: true
  has_many :product_images
  has_many :product_price_tables
  enum status: { pronta_entrega: 1, disponivel: 2, indisponivel: 3, esgotado: 4 }

  accepts_nested_attributes_for :product_images, allow_destroy: true
  #reject_if: lambda {|attributes| attributes['image'].blank?}

  def default_image
    product_images.where(default_image: true).first
  end

  def self.exportar_lista_produtos(lista)
    date = Time.now
    date.strftime("%H:%M:%S %d-%m-%Y")

    csv = CSV.generate(:col_sep => ';', :headers => true) do |row|
      row << ['Codigo', 'Nome', 'Status', 'Tem Imagem ?', 'Quantidade de Imagens']
      lista.each do |produto|
        row << ["#{produto.code}","#{produto.name}","#{produto.status.humanize}", 
          "#{produto.product_images.exists?}","#{produto.product_images.count}"]
        end
      end
      return {csv: csv, date: date}
    end

   def self.importar_produtos(planilha)
     CSV.foreach(planilha.tempfile,:encoding => Encoding::ISO_8859_1, :headers => true) do |row|
       novo_registro = Product.find_or_initialize_by(code: row['Codigo'])
       novo_registro.name = row['Nome']
       novo_registro.status = row['Status']
       novo_registro.save
     end
   end

end

def verifica_imagem_padrao
  product_images.each do |v|
    if v.default_image == true
      break
    else
      product_images[0].default_image = true
      product_images[0].save
    end
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::BaseController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = Product.all.order('name').page(params[:page]).per(9)
    @products = @products.where("name ILIKE ?", "%#{params[:search]}%") if params[:search].present?
  end

  def show
  end

  def new
    @product = Product.new
    @product.product_images.build
  end

  def edit
    puts @product.status
  end

  def create
    @product = Product.new(product_params)
    respond_to do |format|
      if @product.save
        format.html { redirect_to [:admin,@product], notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to [:admin,@product], notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to admin_products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    if params[:padrao].blank?
      params[:padrao] = true
      correct_index = params[:padrao]
    else
      correct_index = params[:padrao][:image_choice]
    end

    params[:product][:product_images_attributes].each do |k, v|
      params[:product][:product_images_attributes][k][:default_image] = (k == correct_index)
    end

    params.require(:product).permit(:code, :name, :status, 
     product_images_attributes:[:id, :image, :default_image, :_destroy])
  end
end

app/helpers/products_helper.rb
module ProductsHelper
  #Verifica se o produto possui uma imagem padrão a ser exibida
  def product_has_image(product)
    if product.product_images.blank?
      imagem_padrao = product.product_images.new
      imagem_padrao.image.default_url
    else
      product.default_image.image.thumb
    end
  end

  def permite_add_produto(product)
    if product.pronta_entrega? || product.disponivel?
      return true
    end
  end

  def quantidade_produto(item)
    id = item.product.id
    valor = current_cart.items.group(:product_id).count
    return valor[id]
  end

  def status_options
    Product.statuses.keys.map { |k| [k.humanize, k] }
  end

  def product_status_badge(product)
    return 'badge-primary' if product.pronta_entrega?
    return 'badge-success' if product.disponivel?
    return 'badge-danger' if product.indisponivel?
    return 'badge-warning' if product.esgotado?
    return 'badge-secondary'
  end

  def tipo_exportacao_produtos(status)
    return "1" if status == "pronta_entrega"
    return "2" if status == "disponivel"
    return "3" if status == "indisponivel"
    return "4" if status == "esgotado"
  end
end

app/views/admin/products/_form.html.erb
<%= form_for [:admin,@product] do |f| %>

<ul>
  <% @product.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
  <% end %>
</ul>

<div class="field">
  <p>
    Code: <%= f.text_field :code, class:"form-control form-control-sm" %>
  </p>

  <p>
    Name: <%= f.text_field :name, class:"form-control form-control-sm" %>
  </p>

  <p>
    Status: <%= f.select :status,options_for_select(status_options)%> 
  </p>
</div>

<%= f.fields_for :product_images do |builder| %>
  <%= render 'product_image_fields', f: builder %>
<% end %>

<br/>
<%= link_to_add_fields "Adicionar Imagens", f, :product_images %>

<br/> <br/>
<p>
  <%= f.submit 'Salvar', class:"btn btn-primary" %>
</p>

<% end %>

app/views/admin/products/_navbar.html.erb
<% if current_administrator.present? %>
<nav class="navbar navbar-expand-lg navbar navbar-dark bg-dark">
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <a class="btn btn-dark dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Menu
    </a>
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
          <%= link_to 'Home', admin_administrators_path, class:"dropdown-item" %>
          <%= link_to 'Tabela de Preço', admin_price_tables_path, class:"dropdown-item" %>
        </div>
      </li>
      <li class="nav-item">
        <%= link_to 'Pedidos', admin_pedidos_path, class:"btn btn-dark" %>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <div class="dropdown">
        <a class="btn btn-dark dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <span> <%= current_administrator.name %> </span>
        </a>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
          <%= link_to 'Logout', admin_logout_path, class:"dropdown-item" %>
        </div>
      </div>
    </form>
  </div>
</nav>
<% end %>

app/views/admin/products/_product_image_fields.html.erb
<fieldset> 
  <div class="card card-body bg"> 
    <% unless f.object.new_record? %>
        <%= image_tag f.object.image.thumb, class:"img-thumbnail", :style => "height:250px;width:250px;"  %> 
        <br/>
    <% end %>
    <%= f.hidden_field :_destroy %>
    <%= link_to "Remover", '#', class: "remove_fields" %> <br/>
    <%= f.file_field :image %> <br/> <br/>

    <%= f.label :default_image, 'Imagem Padrão' %>
    <%= radio_button_tag 'padrao[image_choice]', f.index, f.object.default_image %>
  </div>
</fieldset>


app/views/admin/products/_tabela.html.erb
<table class="table table-striped">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Produto</th>
      <th scope="col">Status</th>
      <th scope="col">Configurações</th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
    <tr>
      <td><%= product.name %></td>
      <td>
        <span class="badge <%= product_status_badge(product) %>">
          <%= product.status.humanize %> 
        </span>
      </td>
      <td>
        <div class="btn-group">
          <%= link_to 'Detalhes', [:admin,product],  class:"btn btn-info" %>
          <button type="button" class="btn btn-info dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="sr-only">Toggle Dropdown</span>
          </button>
          <div class="dropdown-menu">
            <%= link_to 'Editar', edit_admin_product_path(product), class:"dropdown-item" %> 
          </div>
        </div>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Voltar', [:admin,@product], class:"btn btn-warning"%>

app/views/admin/products/index.html.erb
<br/>
<h1>Produtos</h1>
<hr/>

  <%= form_tag("/admin/products", method: "get", remote: :true, id: 'frm_pesquisar') do %>
    <div class="input-group-append">
      <%= text_field_tag(:search, params[:search], class:"form-control form-control-sm", placeholder:"Produto") %>
      &nbsp; &nbsp;
      <%= submit_tag 'Pesquisar', id: 'btnPesquisar', class:"btn btn-primary" %>
    </div>
  <% end %>

<br/>

<div class="row" id="tabela">
  <%= render 'tabela' %>
</div>

<%= link_to 'Novo Produto', new_admin_product_path, class:"btn btn-success" %>

<br/> <br/>

<div id="paginacao"> 
  <%= paginate @products, remote: true ,class:"page-item" %>
</div>

<br/> <br/>

app/views/admin/products/index.js.erb
$('#tabela').html('<%= escape_javascript(render 'tabela') %>');
$('#paginacao').html('<%= escape_javascript(paginate(@products, :remote => true).to_s) %>');

app/views/admin/products/new.html.erb
<h1>Cria Produto</h1>

<%= render 'form' %>

<%= link_to 'Voltar', admin_products_path, class:"btn btn-warning" %>

<br/> <br/>

app/views/admin/products/show.html.erb
<p id="notice"><%= notice %></p>

<h2> Produto </h2>
<hr>

<div id="container">
  <fieldset>
  Código: <%= @product.code %>
  <br/>

  Nome: <%= @product.name %>
  <br/>

  Status: <%= @product.status.humanize %>
  <br/>

  <% if !@product.product_images.blank? %>
    <div align="center" id="containerCarousel" class="carrosel">
      <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">

          <% @product.product_images.each_with_index do |img,index| %>
            <% if index == 0 %>
              <div class="carousel-item active">
                <%= image_tag img.image, alt: index, style:"height:13rem;width: 13rem;" %>  
              </div>
            <% else %>
              <div class="carousel-item">
                <%= image_tag img.image, alt: index, style:"height:13rem;width: 13rem;"  %>  
              </div>
            <% end %>
          <% end %>

          </div>
          <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
            <span id="teste" class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="btn btn-light" class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="btn btn-light" class="sr-only">Next</span>
          </a>
        </div>
      </div>
    </div>
    <% end %>

  </fieldset>

  <br/> <br/>

  <%= link_to 'Editar', edit_admin_product_path(@product),class:"btn btn-info" %> |
  <%= link_to 'Voltar', admin_products_path ,class:"btn btn-warning"%>

  </div>

  <br/> <br/>