config/routes.rb
# == Route Map
#
# You don't have any routes defined!
# 
# Please add some routes in config/routes.rb.
# 
# For more information about routes, see the Rails guide: http://guides.rubyonrails.org/routing.html.
# 

Rails.application.routes.draw do
  scope constraints: lambda { |r| r.env['warden'].user.nil?} do
    get "signup", to: "users#new", as: "signup"
    get "login", to: "sessions#create", as: "login"
  end

  get "logout", to: "sessions#destroy", as: "logout"
  
  root to: "catalog#index"

  resources :users

  resources :sessions

  resources :orders do 
    get 'meus_pedidos', on: :collection
    get 'meus_pedidos/detalhes_pedido/:sales_order_id', to: 'orders#detalhes_pedido', as: 'detalhes_pedido'
  end


  resources :catalog, only: [:index, :show] do 
    get :index2, on: :collection
  end

  get 'meu_carrinho', to: 'cart#meu_carrinho', as: 'meu_carrinho'
  get 'add_quantidade_item', to: 'cart#add_quantidade_item', as: 'add_quantidade_item'
  get 'remove_quantidade_item', to: 'cart#remove_quantidade_item', as: 'remove_quantidade_item'
  get 'altera_quantidade_item', to: 'cart#altera_quantidade_item', as: 'altera_quantidade_item'
  get 'abre_modal', to: 'cart#abre_modal', as: 'abre_modal'

  post 'add_item/:product_id', to: 'cart#add_item', as: 'add_item'
  post 'fecha_pedido', to: 'cart#fecha_pedido', as: 'fecha_pedido'

  delete 'remove_item', to: 'cart#remove_item', as: 'remove_item'
  delete 'limpa_carrinho', to: 'cart#limpa_carrinho', as: 'limpa_carrinho'

  namespace :admin do
    resources :administrators
    resources :products
    resources :sessions
    resources :price_tables do
      resources :product_price_tables  
    end

    get 'login', to: 'sessions#new', as: 'login'
    post 'login', to: 'sessions#create', as: 'authenticate'
    get 'logout', to: 'sessions#destroy', as: 'logout'

    get 'pedidos', to: 'dashboard#pedidos', as: 'pedidos'
    get 'pedidos/detalhes_pedido/:pedido_id', to: 'dashboard#detalhes_pedido', as: 'detalhes_pedido'
    get 'exportar_lista_produtos', to: 'dashboard#exportar_lista_produtos', as: 'exportar_lista_produtos'
    post 'importar_produtos', to: 'dashboard#importar_produtos', as: 'importar_produtos'
  end

end

app/controllers/admin/price_tables_controller.rb
class Admin::PriceTablesController < Admin::BaseController
  before_action :set_price_table, only: [:show, :edit, :update, :destroy]

  def index
    @price_tables = PriceTable.all
  end

  def show
    @product_price_tables = @price_table.product_price_tables
    @product_price_tables = @product_price_tables.page(params[:page]).per(2)
  end

  def new
    @price_table = PriceTable.new
  end

  def edit
  end

  def create
    @price_table = PriceTable.new(price_table_params)
    respond_to do |format|
      if @price_table.save
        format.html { redirect_to [:admin,@price_table], notice: 'Price table was successfully created.' }
        format.json { render :show, status: :created, location: @price_table }
      else
        format.html { render :new }
        format.json { render json: @price_table.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @price_table.update(price_table_params)
        format.html { redirect_to [:admin,@price_table], notice: 'Price table was successfully updated.' }
        format.json { render :show, status: :ok, location: @price_table }
      else
        format.html { render :edit }
        format.json { render json: @price_table.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @price_table.destroy
    respond_to do |format|
      format.html { redirect_to admin_price_tables_path, notice: 'Price table was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_price_table
      @price_table = PriceTable.find(params[:id])
    end

    def price_table_params
      params.require(:price_table).permit(:id,:name, :initial_date, :end_date, 
                     product_price_tables:[:id,:price, :product_id, :price_tables_id])
    end
end

app/helpers/price_tables_helper.rb
module PriceTablesHelper
end

app/views/admin/price_tables/_form.html.erb
<%= form_for([:admin, @price_table]) do |f| %>

<ul>
  <% @price_table.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
  <% end %>
</ul>

<div class="field">
  <p>
    Nome: <%= f.text_field :name, class:"form-control form-control-sm"  %>
  </p>

  <p>
    Data Inicio: <%= f.date_field :initial_date, class:"form-control form-control-sm" %>
  </p>

  <p>
    Data Fim: <%= f.date_field :end_date, class:"form-control form-control-sm" %>
  </p>
</div>

<br/> <br/>
<p>
  <%= f.submit 'Salvar', class:"btn btn-primary"%>
</p>

<% end %>

app/views/admin/price_tables/_navbar.html.erb
<% if current_administrator.present? %>
<nav class="navbar navbar-expand-lg navbar navbar-dark bg-dark">
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <a class="btn btn-dark dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Menu
    </a>
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
          <%= link_to 'Home', admin_administrators_path, class:"dropdown-item" %>
          <%= link_to 'Produtos', admin_products_path, class:"dropdown-item" %>
        </div>
      </li>
      <li class="nav-item">
        <%= link_to 'Pedidos', admin_pedidos_path, class:"btn btn-dark" %>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <div class="dropdown">
        <a class="btn btn-dark dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <span> <%= current_administrator.name %> </span>
        </a>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
          <%= link_to 'Logout', admin_logout_path, class:"dropdown-item" %>
        </div>
      </div>
    </form>
  </div>
</nav>
<% end %>

app/views/admin/price_tables/_precos_tabela.html.erb
    <table class="table table-striped">
      <thead class="thead-dark">
        <tr>
          <th scope="col">Produto</th>
          <th scope="col">Preço</th>
          <th scope="col">Configurações</th>
        </tr>
      </thead>
      <tbody>
        <% @product_price_tables.each do |ppt| %>
        <tr>
          <td><%= ppt.product.name %></td>
          <td>R$ <%= ppt.price %></td>
          <td>
              <%= link_to 'Editar', edit_admin_price_table_product_price_table_path(@price_table, ppt),
                class: "btn btn-light", remote: true %>
              <%= link_to 'Remover', admin_price_table_product_price_table_path(@price_table, ppt), remote: :true, method: :delete, data: { confirm: "Deseja realmente excluir?" }, class: "btn btn-danger" %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>

app/views/admin/price_tables/edit.html.erb
<h1>Editar Tabela de Preço</h1>

<%= render 'form', price_table: @price_table %>

<%= link_to 'Voltar', admin_price_table_path(@price_table), class:"btn btn-warning" %>

app/views/admin/price_tables/index.html.erb
<p id="notice"><%= notice %></p>

<br/>

<h1>Tabelas de Preço</h1>

<br/> <br/>

<div class="row">
    <div class="card card-body bg-light">
      <table class="table table-hover">
        <thead class="thead-dark">
          <tr>
            <th> Nome </th>
            <th> Data Inicio </th>
            <th> Data Fim </th>
            <th> Configurações </th>
          </tr>
        </thead>

        <tbody>
          <% @price_tables.each do |price_table| %>
          <tr>
            <td> <%= price_table.name %> </td>
            <td> <%= price_table.initial_date.strftime("%d/%m/%Y") %> </td>
            <td> <%= price_table.end_date.strftime("%d/%m/%Y") %> </td>
            <td>
              <div class="btn-group">
                <%= link_to 'Detalhes', admin_price_table_path(price_table), class:"btn btn-secondary" %>
                <button type="button" class="btn btn-secondary dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true"  aria-expanded="false">
                  <span class="sr-only">Toggle Dropdown</span>
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                  <%= link_to 'Editar', edit_admin_price_table_path(price_table), class:"dropdown-item" %>
                  <div class="dropdown-divider"></div>
                  <%= link_to 'Excluir',  [:admin,price_table], method: :delete, 
                  data: { confirm: 'Certeza ?' }, class:"dropdown-item" %>

                </div>
              </div>
            </td>
          </div>
        </div>
      </tr>
      <% end %>
    </tbody>
  </table>

</div>
</div>

<br/>

<%= link_to 'Nova Tabela de Preço', new_admin_price_table_path, class:"btn btn-success" %>

app/views/admin/price_tables/new.html.erb
<h1>Nova Tabela de Preço</h1>

<%= render 'form', price_table: @price_table %>

<%= link_to 'Voltar', admin_price_tables_path, class:"btn btn-warning" %>

app/views/admin/price_tables/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Tabela de Preço</h1>
<hr/>

<br/>

<div class='table-responsive'>
  <table class="table table-striped">
    <thead class="thead-dark">
      <tr>
        <th scope="col">Nome</th>
        <th scope="col">Data Inicio</th>
        <th scope="col">Data Fim</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= @price_table.name %></td>
        <td><%= @price_table.initial_date.strftime("%d/%m/%Y") %></td>
        <td><%= @price_table.end_date.strftime("%d/%m/%Y") %></td>
      </tr>
    </tbody>
  </table>
</div>

<%= link_to 'Editar', edit_admin_price_table_path(@price_table), class:"btn btn-secondary" %> 
<%= link_to 'Voltar', admin_price_tables_path, class:"btn btn-secondary" %> 

<hr/>
<br/>

<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Produto</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="modalBody">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
        <button type="submit" class="btn btn-secondary" form="frmProductPrice" value="Submit">Salvar</button>
      </div>
    </div>
  </div>
</div>
 
   <%= link_to 'Cadastrar Preços', new_admin_price_table_product_price_table_path(@price_table), 
    class: "btn btn-primary", remote: true %>

<hr/>
<br/>

<div class="card card-body bg-light">
  <h1>Produtos</h1>
  <hr/>

  <%= form_tag(admin_price_table_product_price_tables_path(@price_table), method: "get", remote: :true, id: 'frm_pesquisar') do %>
    <div class="input-group-append">
      <%= text_field_tag(:search, params[:search], class:"form-control form-control-sm", placeholder:"Produto") %>
      &nbsp; &nbsp;
      <%= submit_tag 'Pesquisar', id: 'btnPesquisar', class:"btn btn-primary" %>
    </div>
  <% end %>

  <br/>

  <div class='table-responsive' id='product_price_tables'>
    <%= render 'precos_tabela' %>
  </div>

  <br/> 

  <div id="paginacao"> 
    <%= paginate @product_price_tables, remote: true , class:"page-item" %>
  </div>

</div>

<br/>

app/views/admin/price_tables/show.js.erb
$('#product_price_tables').html('<%= escape_javascript(render 'precos_tabela') %>');
$('#paginacao').html('<%= escape_javascript(paginate(@product_price_tables, :remote => true).to_s) %>');